version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    working_directory: ~/rails-docker-prn/src
    steps:
      - checkout:
          path: ~/rails-docker-prn
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
            PGHOST: localhost
            PGUSER: rails-docker-prn
            RAILS_ENV: test
      - image: circleci/postgres:13.6
        environment:
          POSTGRES_USER: rails-docker-prn
          POSTGRES_PASSWORD: ""
          POSTGRES_DATABASE: src_test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/rails-docker-prn/src
    steps:
      - checkout:
          path: ~/rails-docker-prn
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      